version: '3.7'

services:
  minio1:
    image: minio/minio
    hostname: minio1
    volumes:
      - minio1-data:/export
#    ports:
#      - "9001:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio1==true
      labels:
        - traefik.frontend.rule=Host:minio.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}.${DOMAIN}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    hostname: minio2
    volumes:
      - minio2-data:/export
#    ports:
#      - "9002:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio2==true
      labels:
        - traefik.frontend.rule=Host:minio2.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio
    hostname: minio3
    volumes:
      - minio3-data:/export
#    ports:
#      - "9003:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio3==true
      labels:
        - traefik.frontend.rule=Host:minio3.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio
    hostname: minio4
    volumes:
      - minio4-data:/export
#    ports:
#      - "9004:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio4==true
      labels:
        - traefik.frontend.rule=Host:minio4.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio5:
    image: jessestuart/minio
    hostname: minio5
    volumes:
      - minio5-data:/export
#    ports:
#      - "9005:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio5==true
      labels:
        - traefik.frontend.rule=Host:minio5.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio6:
    image: jessestuart/minio
    hostname: minio6
    volumes:
      - minio6-data:/export
#    ports:
#      - "9006:9000"
    networks:
      - minio_distributed
      - traefik-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:
        constraints:
          - node.labels.minio6==true
      labels:
        - traefik.frontend.rule=Host:minio6.${DOMAIN}
        - traefik.enable=true
        - traefik.port=9000
        - traefik.tags=public
        - traefik.docker.network=traefik-net
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    command: server http://minio{1...6}/export
#    command: minio server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
      # See 'REX-Ray Docker volume plug-ins' documentaion; volume available across entire docker swarm cluster
      # https://rexray.readthedocs.io/en/v0.9.0/user-guide/docker-plugins/#elastic-block-service
      # driver: rexray/ebs
      # driver_opts:
      #   size: 5
  minio1-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/Volumes

  minio2-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/Volumes

  minio3-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/Volumes

  minio4-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /media/Volumes

  minio5-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/Volumes

  minio6-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/storage/Volumes

networks:
  minio_distributed:
    driver: overlay
  traefik-net:
    external: true


secrets:
  secret_key:
    external: true
  access_key:
    external: true
