version: "3.7"

networks:
  traefik-net:
    external: true

services:
  booksonic:
    image: linuxserver/booksonic
    environment:
      - JAVA_OPTS=-Dserver.use-forward-headers=true      
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CONTEXT_PATH=url-base
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - othermedia:/othermedia
      - config:/config
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.hostname == docker]
      labels:
        - traefik.frontend.rule=Host:booksonic.${DOMAIN}
        - traefik.enable=true
        - traefik.port=4040
        - traefik.tags=traefik-net
        - traefik.docker.network=traefik-net
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.SSLHost=booksonic.${DOMAIN}
        - traefik.frontend.headers.SSLForceHost=true
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

volumes:
    audiobooks:
    podcasts:
    othermedia:
    config:
    
