version: "3.7"

networks:
  traefik-net:
    external: true

services:
  booksonic:
    image: linuxserver/booksonic
    environment:
      - JAVA_OPTS=-Dserver.use-forward-headers=true
    volumes:
      - /media/Audio/Audiobooks/Fiction:/books
      - /media/Audio/Audiobooks:/media
      - /media/Audio/podcasts:/podcasts
      - /media/Audio/playlists:/playlists
      - /home/tim/booksonic:/config
      - /etc/timezone:/etc/timezone:ro
      - /home/tim/shared:/shared
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.hostname == docker]
      labels:
        - traefik.frontend.rule=Host:booksonic.mullinskelley.com
        - traefik.enable=true
        - traefik.port=4040
        - traefik.tags=traefik-net
        - traefik.docker.network=traefik-net
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.SSLHost=booksonic.mullinskelley.com
        - traefik.frontend.headers.SSLForceHost=true
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
