---
version: "2"
services:
  organizr:
    image: linuxserver/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=your timezone, eg Europe/London
    volumes:
      - path to data:/config
    ports:
      - 9983:80
    restart: unless-stopped
