version: "3.7"

networks:
  traefik-net:
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    environment:
      - CONTEXT_PATH=url-base
    volumes:
#      - mosquitto.conf:/mosquitto/config/mosquitto.conf
      - config:/mosquitto/config
      - data:/mosquitto/data
      - log:/mosquitto/log
    networks:
      - traefik-net
    deploy:
      placement:
        constraints: [node.hostname == docker]
      labels:
        - traefik.frontend.rule=Host:mqtt.${DOMAIN}
        - traefik.enable=true
        - traefik.port=1883
        - traefik.tags=traefik-net
        - traefik.docker.network=traefik-net
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.SSLHost=mqtt.${DOMAIN}
        - traefik.frontend.headers.SSLForceHost=true
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.customFrameOptionsValue=SAMEORIGIN
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

volumes:
#    mosquitto.conf:
    config:
    data:
    log:
